// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgpC-80Fc61Ehy8ewHKZuk2j5CPKu34t0',
    appId: '1:623948250926:web:ba3f08c5cfe806afa884bf',
    messagingSenderId: '623948250926',
    projectId: 'workout-tracker-fcc9d',
    authDomain: 'workout-tracker-fcc9d.firebaseapp.com',
    storageBucket: 'workout-tracker-fcc9d.appspot.com',
    measurementId: 'G-G1FV1BCMZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC795r5fZ-ueMS1vsJqKWvIaIQM4bo-71s',
    appId: '1:623948250926:android:7d844b787d28041ca884bf',
    messagingSenderId: '623948250926',
    projectId: 'workout-tracker-fcc9d',
    storageBucket: 'workout-tracker-fcc9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwvlDAkbYJVpqYIiABDRt6B3og9anyol8',
    appId: '1:623948250926:ios:ab310fa62f95bb17a884bf',
    messagingSenderId: '623948250926',
    projectId: 'workout-tracker-fcc9d',
    storageBucket: 'workout-tracker-fcc9d.appspot.com',
    iosClientId: '623948250926-uj8rcmu0v3u36etvufmb28d5f2ke0umn.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwvlDAkbYJVpqYIiABDRt6B3og9anyol8',
    appId: '1:623948250926:ios:ab310fa62f95bb17a884bf',
    messagingSenderId: '623948250926',
    projectId: 'workout-tracker-fcc9d',
    storageBucket: 'workout-tracker-fcc9d.appspot.com',
    iosClientId: '623948250926-uj8rcmu0v3u36etvufmb28d5f2ke0umn.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutTracker',
  );
}
